### PR TITLE
Fix abnf repetition issue

### LINKED ISSUE #58: fieldContentRule does not work
`
[ 1*( SP / HTAB / field-vchar ) field-vchar ]
`
This breaks because field-vchar is matching in the repetition and then the sequence fails.

### PR DESCRIPTION
**Pull request by DavidPoetsch**
Created new EndRule that can be used after an RepetitionRule
* Fixes #58

```c++
  ft::shared_ptr<SequenceRule> optSeq = ft::make_shared<SequenceRule>();
  optSeq->setDebugTag("[1*(SP/HTAB/field-vchar)field-vchar]");
  optSeq->addRule(ft::move(repeatPart));

  ft::shared_ptr<EndRule> endVchar = ft::make_shared<EndRule>(fieldVcharRule());
  endVchar->setDebugTag("endVchar");
  optSeq->addRule(ft::move(endVchar));
  ```

### CODE REVIEW

File: src/utils/abnfRules/EndRule.cpp [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+    }
+    matches = _rule->matches();
+    if (matches && getEndPos() == getBuffReader()->getPosInBuff()) {
+      break;
+    }
+    getBuffReader()->setPosInBuff(getEndPos());
+    rewindCount++;
+    matches = false;
+  }
+  moveToEndPos();
```
Comment (itislu) [inline src/utils/abnfRules/EndRule.cpp]:
```suggestion
    moveToEndPos();
    rewindCount++;
    matches = false;
  }
  moveToEndPos();
```

File: tests/http/abnfRules/headerLineRulesTester.cpp [hunk 2]
```diff
@@ -33,25 +34,57 @@ bool runParser(const std::string& str, Rule& rule)
...
+
+  // Invalid
+  EXPECT_FALSE(runParser("test  \n", *rule)); // must end with vchar
+  EXPECT_FALSE(rule->reachedEnd());
+}
+
 TEST(HeaderLinesTester, FieldValueRule)
 {
+  const ft::shared_ptr<SequenceRule> seqRule = ft::make_shared<SequenceRule>();
   const ft::shared_ptr<RepetitionRule> rule = fieldValueRule();
```
Comment (itislu) [inline tests/http/abnfRules/headerLineRulesTester.cpp]: Unused.
```suggestion
```

**Review by itislu — CHANGES_REQUESTED** [review]

File: tests/http/abnfRules/headerLineRulesTester.cpp [hunk 3]
```diff
@@ -33,25 +34,57 @@ bool runParser(const std::string& str, Rule& rule)
...
+  const ft::shared_ptr<SequenceRule> seqRule = ft::make_shared<SequenceRule>();
+  seqRule->addRule(fieldLineRule());
+  seqRule->addRule(ft::make_shared<RangeRule>("\n"));
 
-  EXPECT_TRUE(runParser("host: test, hallo", *rule));
+  EXPECT_TRUE(runParser("host: test, hallo\n", *seqRule));
+
+  // Invalid
+  EXPECT_FALSE(
+    runParser("host: test, hallo \n", *seqRule)); // must end with vchar
```
[the remark this answers is not in the document]
Comment (DavidPoetsch) [reply tests/http/abnfRules/headerLineRulesTester.cpp]: image

maybe it is better to parse it later.
Then i can parse it depending on the HeaderField ?!

**Review by itislu — APPROVED** [review]
